
nav:
  - Home: 'index.md'
  - Slaughtercraft:
    - Index: 'slaughtercraft/index.md'
    - Blocks:
      - Carcasses: 'slaughtercraft/blocks/carcasses.md'
      - Other Blocks: 'slaughtercraft/blocks/otherblocks.md'
    - Items:
      - Butchers Knife: 'slaughtercraft/items/butchersknife.md'
      - Food and Animal Parts: 'slaughtercraft/items/animalparts.md'
    - Misc:
      - Recipes: 'slaughtercraft/misc/recipes.md'
  - Gemsplusplus:
    - Index: 'gemsplusplus/index.md'
  - Reinforced Blocks Mod 2:
    - Index: 'reinforcedblocksmod2/index.md'



site_name: Trhod177's Mods Documentation

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true

theme:
  name: 'material'
  custom_dir: 'theme'
  palette:
    primary: 'green'
    accent: 'light green'
  favicon: 'assets/images/favicon.ico'
  logo: 'assets/images/logo.svg'


extra_css:
  - stylesheets/dark_theme.css
  - stylesheets/codehilite.css
  - stylesheets/custom.css
