
nav:
  - Home: 'index.md'
  - Slaughtercraft:
    - Index: 'slaughtercraft/index.md'
    - Blocks:
      - Carcasses: 'slaughtercraft/blocks/carcasses.md'
      - Other Blocks: 'slaughtercraft/blocks/otherblocks.md'
    - Items:
      - Butchers Knife: 'slaughtercraft/items/butchersknife.md'
      - Food and Animal Parts: 'slaughtercraft/items/animalparts.md'
    - Misc:
      - Recipes: 'slaughtercraft/misc/recipes.md'
  - Gemsplusplus:
    - Index: 'gemsplusplus/index.md'
    - Blocks:
      - Gem Blocks: 'gemsplusplus/blocks/gemblock.md'
      - Gem Glass: 'gemsplusplus/blocks/glass.md'
      - Gem Sand: 'gemsplusplus/blocks/sand.md'
      - Gem Ore: 'gemsplusplus/blocks/ores.md'
    - Armour:
      - Agate Armour: 'gemsplusplus/armour/agatearmour.md'
      - Amethyst Armour: 'gemsplusplus/armour/amethystarmour.md'
      - Citrine Armour: 'gemsplusplus/armour/citrinearmour.md'
      - Chrysocolla Armour: 'gemsplusplus/armour/chrysocollaarmour.md'
      - Garnet Armour: 'gemsplusplus/armour/garnetarmour.md'
      - Jade Armour: 'gemsplusplus/armour/jadearmour.md'
      - Jasper Armour: 'gemsplusplus/armour/jasperarmour.md'
      - Malachite Armour: 'gemsplusplus/armour/malachitearmour.md'
      - Onyx Armour: 'gemsplusplus/armour/onyxarmour.md'
      - Phoenixite Armour: 'gemsplusplus/armour/phoenixitearmour.md'
      - Ruby Armour: 'gemsplusplus/armour/rubyarmour.md'
      - Sapphire Armour: 'gemsplusplus/armour/sapphirearmour.md'
      - Spinel Armour: 'gemsplusplus/armour/spinelarmour.md'
      - Sugilite Armour: 'gemsplusplus/armour/sugilitearmour.md'
      - Topaz Armour: 'gemsplusplus/armour/topazarmour.md'
      - Tourmaline Armour: 'gemsplusplus/armour/tourmalinearmour.md'
  - Reinforced Blocks Mod 2:
    - Index: 'reinforcedblocksmod2/index.md'



site_name: Trhod177's Mods Documentation

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true

theme:
  name: 'material'
  custom_dir: 'theme'
  palette:
    primary: 'green'
    accent: 'light green'
  favicon: 'assets/images/favicon.ico'
  logo: 'assets/images/logo.svg'


extra_css:
  - stylesheets/dark_theme.css
  - stylesheets/codehilite.css
  - stylesheets/custom.css
