
nav:
  - Home: 'index.md'
  - Slaughtercraft:
    - Index: 'slaughtercraft/index.md'
    - Blocks:
      - Carcasses: 'slaughtercraft/blocks/carcasses.md'
      - Other Blocks: 'slaughtercraft/blocks/otherblocks.md'
    - Items:
      - Butchers Knife: 'slaughtercraft/items/butchersknife.md'
      - Food and Animal Parts: 'slaughtercraft/items/animalparts.md'
    - Misc:
      - Recipes: 'slaughtercraft/misc/recipes.md'
  - Gems++:
    - Index: 'gemsplusplus/index.md'
    - Blocks:
      - Gem Blocks: 'gemsplusplus/blocks/gemblock.md'
      - Gem Glass: 'gemsplusplus/blocks/glass.md'
      - Gem Sand: 'gemsplusplus/blocks/sand.md'
      - Gem Ore: 'gemsplusplus/blocks/ores.md'
    - Items:
      - Gem Armour: 'gemsplusplus/items/armour.md'
      - Gems: 'gemsplusplus/items/gems.md'
      - Tools: 'gemsplusplus/items/tools.md'

      
site_name: Trhod177's Mods Documentation !!(Under Construction)!!

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true

theme:
  name: 'material'
  custom_dir: 'theme'
  palette:
    primary: 'green'
    accent: 'light green'
  favicon: 'assets/images/favicon.ico'
  logo: 'assets/images/logo.svg'


extra_css:
  - stylesheets/dark_theme.css
  - stylesheets/codehilite.css
  - stylesheets/custom.css
