
nav:
  - Home: 'index.md'
  - Slaughtercraft:
    - Home: 'slaughtercraft/index.md'
    - Blocks:
      - Carcasses: 'slaughtercraft/blocks/carcasses.md'
      - Other Blocks: 'slaughtercraft/blocks/otherblocks.md'
    - Items:
      - Butchers Knife: 'slaughtercraft/items/butchersknife.md'
      - Animal Parts: 'slaughtercraft/items/animalparts.md'
  - Gemsplusplus:
    - Home: 'gemsplusplus/index.md'


site_name: Trhod177's Mods Documentation

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true


theme:
  name: 'material'
  custom_dir: 'theme'
  palette:
    primary: 'green'
    accent: 'light green'
  favicon: 'assets/images/favicon.ico'
  logo: 'assets/images/logo.svg'


extra_css:
  - stylesheets/dark_theme.css
  - stylesheets/codehilite.css
  - stylesheets/custom.css
