
nav:
  - Home: 'index.md'
  - Slaughtercraft:
    - Home: 'slaughtercraft/index.md'
    - Blocks:
      - Carcasses: 'slaughtercraft/blocks/carcasses.md'
      - Other Blocks: 'slaughtercraft/blocks/otherblocks.md'
  - Gemsplusplus:
    - Home: 'gemsplusplus/index.md'


site_name: Trhod177's Mods Documentation

markdown_extensions:
    - pymdownx.tasklist

theme:
  name: 'material'
  custom_dir: 'theme'
  palette:
    primary: 'green'
    accent: 'light green'

extra_css:
  - stylesheets/dark_theme.css
  - stylesheets/codehilite.css
  - stylesheets/custom.css
